$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
name: production-model-training-1
displayName: Production Job Training
code: model
command: >-
  python train.py
  --training_data ${{inputs.training_data}}
  --reg_rate ${{inputs.reg_rate}}
inputs: 
  training_data:
    type: uri_folder
    path: azureml:diabetes-prod-folder:1
  reg_rate: 0.01 
environment: azureml://registries/azureml/environments/sklearn-1.5/versions/26
compute: azureml:ML-compute-1-mlops
experiment_name: Production-Job
description: Training diabetes classification using production dataset
