name: Triggered training by push

# on:
#   pull_request:
#     types: [opened, synchronize, reopened]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Install az ml extension
        run: az extension add -n ml -y

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Submit Azure ML job 
        run: |
          az ml job create --file src/job.yml \
          --resource-group ml_studio_rg \
          --workspace-name ml_work_place_1
