name: Workflow Dev-Prod 
on: 
  push:
    branches:
      - main
jobs:
  job1:
    name: Development Job 
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Check out repo - dev
        uses: actions/checkout@v3

      - name: Set up python - dev
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Azure CLI - dev
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Install azure ml extension
        run: az extension add -n ml -y

      - name: Azure login - dev
        uses: azure/login@v1 
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Submit Azure ML job - Development 
        run: |
          az ml job create --file src/dev_job.yml \
          --resource-group ml_studio_rg \
          --workspace-name test-workspace \
          --stream

  job2:
    name: Production Job
    needs: job1
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Check out repo - prod
        uses: actions/checkout@v3

      - name: Set up python - prod
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Azure CLI - prod
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Install azure ml extension - prod
        run: az extension add -n ml -y

      - name: Azure login - prod
        uses: azure/login@v1 
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Submit Azure ML job - Production 
        run: |
          az ml job create --file src/prod_job.yml \
          --resource-group ml_studio_rg \
          --workspace-name test-workspace \
          --stream
